//#define RTG_CACHE_POLICY NORM_WB_CACHE
#define NC 0b00
#define WB 0b01
#define WT 0b10
#define WBNWA 0b11
#define OUTER 12
#define INNER 2

#define RTG_FB_CACHE_POLICY_FOR_060 (0x14DE2|(WT<<OUTER)|(WT<<INNER))
#define RTG_SOFT3D_CACHE_POLICY_FOR_060 (0x14DE2|(WB<<OUTER)|(WB<<INNER))

#define RTG_FB_CACHE_POLICY_FOR_EMU (0x14DE2|(WT<<OUTER)|(WT<<INNER))
#define RTG_SOFT3D_CACHE_POLICY_FOR_EMU (0x14DE2|(WB<<OUTER)|(WB<<INNER))

#define ETHERNET_CACHE_POLICY (0x14DE2|(NC<<OUTER)|(NC<<INNER))
#define AUDIO_CACHE_POLICY (0x14DE2|(WT<<OUTER)|(WT<<INNER))

#define RAM_CACHE_POLICY (0x14DE2|(WB<<OUTER)|(WB<<INNER))
