#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Sat Nov 22 20:09:01 +0100 2025
# SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_15 -libname processing_system7_vip_v1_0_17 -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname lib_pkg_v1_0_3 -libname fifo_generator_v13_2_9 -libname lib_fifo_v1_0_18 -libname blk_mem_gen_v8_4_7 -libname lib_bmg_v1_0_16 -libname lib_srl_fifo_v1_0_3 -libname axi_datamover_v5_1_31 -libname axi_vdma_v6_3_17 -libname axis_infrastructure_v1_1_1 -libname axis_data_fifo_v2_0_11 -libname util_vector_logic_v2_0_3 -libname xlconcat_v2_1_5 -libname xlslice_v1_0_3 -libname audio_formatter_v1_0_11 -libname axi_register_slice_v2_1_29 -libname axis_register_slice_v1_1_29 -libname i2s_transmitter_v1_0_7 -libname generic_baseblocks_v2_1_1 -libname axi_data_fifo_v2_1_28 -libname axi_protocol_converter_v2_1_29 -libname axi_clock_converter_v2_1_28 -libname axi_dwidth_converter_v2_1_29 -libname axi_crossbar_v2_1_30 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_15 processing_system7_vip_v1_0_17 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 lib_pkg_v1_0_3 fifo_generator_v13_2_9 lib_fifo_v1_0_18 blk_mem_gen_v8_4_7 lib_bmg_v1_0_16 lib_srl_fifo_v1_0_3 axi_datamover_v5_1_31 axi_vdma_v6_3_17 axis_infrastructure_v1_1_1 axis_data_fifo_v2_0_11 util_vector_logic_v2_0_3 xlconcat_v2_1_5 xlslice_v1_0_3 audio_formatter_v1_0_11 axi_register_slice_v2_1_29 axis_register_slice_v1_1_29 i2s_transmitter_v1_0_7 generic_baseblocks_v2_1_1 axi_data_fifo_v2_1_28 axi_protocol_converter_v2_1_29 axi_clock_converter_v2_1_28 axi_dwidth_converter_v2_1_29 axi_crossbar_v2_1_30)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_17 $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_1_0/sim/design_1_proc_sys_reset_1_0.vhd" \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/sim/design_1_rst_ps7_0_200M_1_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_18 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_bmg_v1_0_16 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/5c9c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_31 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vdma_v6_3_17 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_vdma_v6_3_17 $xmvhdl_opts \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_vdma_0_1/sim/design_1_axi_vdma_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_data_fifo_v2_0_11 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/68dc/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work util_vector_logic_v2_0_3 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/5e7b/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_util_vector_logic_0_1/sim/design_1_util_vector_logic_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_1/sim/design_1_xlconcat_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlslice_v1_0_3 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/217a/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
  "../../../bd/design_1/ip/design_1_video_formatter_0_0/sim/design_1_video_formatter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/sim/design_1_rst_ps7_0_200M_1_2.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work audio_formatter_v1_0_11 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/d22b/hdl/audio_formatter_v1_0_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_audio_formatter_0_0/sim/design_1_audio_formatter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_register_slice_0_0_1/sim/design_1_axi_register_slice_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_register_slice_v1_1_29 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/af18/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_register_slice_0_0/sim/design_1_axis_register_slice_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work i2s_transmitter_v1_0_7 $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/bf6a/hdl/i2s_transmitter_v1_0_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_i2s_transmitter_0_0/sim/design_1_i2s_transmitter_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_conv_funs_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_proc_common_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_ipif_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family_support.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_soft_reset.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_pselect_f.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_address_decoder.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_slave_attachment.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_axi_lite_ipif.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz_drp.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_conv_funs_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_proc_common_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_ipif_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_family_support.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_family.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_soft_reset.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_2_0_pselect_f.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_2_0_address_decoder.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_2_0_slave_attachment.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_2_0_axi_lite_ipif.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_clk_wiz_drp.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0.v" \
  "../../../bd/design_1/ip/design_1_cpuclk_iob_0_0/sim/design_1_cpuclk_iob_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_200M_0/sim/design_1_rst_ps7_0_200M_0.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_conv_funs_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_proc_common_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_ipif_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family_support.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_soft_reset.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_pselect_f.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_address_decoder.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_slave_attachment.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/interrupt_control_v2_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_interrupt_control.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_axi_lite_ipif.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0_xadc_core_drp.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0_axi_xadc.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_28 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_28 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/769c/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_dwidth_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/670d/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/sim/design_1_axi_dwidth_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axi_protocol_convert_0_0/sim/design_1_axi_protocol_convert_0_0.v" \
  "../../../bd/design_1/ip/design_1_axi_register_slice_0_1/sim/design_1_axi_register_slice_0_1.v" \
  "../../../bd/design_1/ip/design_1_axi_register_slice_1_0/sim/design_1_axi_register_slice_1_0.v" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_2/sim/design_1_xlconcat_0_2.v" \
  "../../../bd/design_1/ip/design_1_z3660_0_0/sim/design_1_z3660_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_30 $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../z3660.gen/sources_1/bd/design_1/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../z3660.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  "../../../bd/design_1/ip/design_1_s00_regslice_115/sim/design_1_s00_regslice_115.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  "../../../bd/design_1/ip/design_1_s00_regslice_114/sim/design_1_s00_regslice_114.v" \
  "../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  "../../../bd/design_1/ip/design_1_s00_regslice_116/sim/design_1_s00_regslice_116.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
