M48
; DRILL file {KiCad (6.0.5-0)} date Friday, 01 July 2022 at 16:01:17
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-01T16:01:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X4.0472Y-4.6381
X5.82Y-3.365
T2
X9.3503Y-4.644
T3
X3.3331Y-1.5471
X3.3336Y-4.2741
X9.8331Y-1.5498
X9.8331Y-4.2741
T0
M30
