
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#ifndef __BSPCONFIG_H_
#define __BSPCONFIG_H_

/*
 * Definition to indicate that current BSP is a FreeRTOS BSP which can be used to
 * distinguish between standalone BSP and FreeRTOS BSP.
 */
#define FREERTOS_BSP

#endif /*end of __BSPCONFIG_H_*/
