#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 1U

/* Definitions for peripheral PS7_CORTEXA9_1 */
#define XPAR_PS7_CORTEXA9_1_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_1 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQ
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver AUDIO_FORMATTER */
#define XPAR_XAUDIOFORMATTER_NUM_INSTANCES 1

/* Definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0 */
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_DEVICE_ID 0
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_BASEADDR 0x7FC00000
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_HIGHADDR 0x7FC0FFFF
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_INCLUDE_MM2S 1
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_INCLUDE_S2MM 0
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_MAX_NUM_CHANNELS_MM2S 2
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_MAX_NUM_CHANNELS_S2MM 2
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_MM2S_ADDR_WIDTH 32
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_MM2S_DATAFORMAT 3
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_PACKING_MODE_MM2S 0
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_PACKING_MODE_S2MM 0
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_S2MM_ADDR_WIDTH 64
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_S2MM_DATAFORMAT 1


/******************************************************************/

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0 */
#define XPAR_XAUDIOFORMATTER_0_NUM_INSTANCES 0
#define XPAR_XAUDIOFORMATTER_0_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_DEVICE_ID
#define XPAR_XAUDIOFORMATTER_0_BASEADDR 0x7FC00000
#define XPAR_XAUDIOFORMATTER_0_HIGHADDR 0x7FC0FFFF
#define XPAR_XAUDIOFORMATTER_0_INCLUDE_MM2S 1
#define XPAR_XAUDIOFORMATTER_0_INCLUDE_S2MM 0
#define XPAR_XAUDIOFORMATTER_0_MAX_NUM_CHANNELS_MM2S 2
#define XPAR_XAUDIOFORMATTER_0_MAX_NUM_CHANNELS_S2MM 2
#define XPAR_XAUDIOFORMATTER_0_MM2S_ADDR_WIDTH 32
#define XPAR_XAUDIOFORMATTER_0_MM2S_DATAFORMAT 3
#define XPAR_XAUDIOFORMATTER_0_PACKING_MODE_MM2S 0
#define XPAR_XAUDIOFORMATTER_0_PACKING_MODE_S2MM 0
#define XPAR_XAUDIOFORMATTER_0_S2MM_ADDR_WIDTH 64
#define XPAR_XAUDIOFORMATTER_0_S2MM_DATAFORMAT 1


/******************************************************************/

/* Definitions for driver AXIVDMA */
#define XPAR_XAXIVDMA_NUM_INSTANCES 1U

/* Definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0 */
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_DEVICE_ID 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_BASEADDR 0x7FC80000U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_HIGHADDR 0x7FC8FFFFU
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_NUM_FSTORES 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_MM2S 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_MM2S_DRE 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_M_AXI_MM2S_DATA_WIDTH 32U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_S2MM 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_S2MM_DRE 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_MM2S_GENLOCK_MODE 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_S2MM_GENLOCK_MODE 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_S2MM_GENLOCK_NUM_MASTERS 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_SG 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_VIDPRMTR_READS 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_USE_FSYNC 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_FLUSH_ON_FSYNC 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_S2MM_LINEBUFFER_DEPTH 512U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_INCLUDE_INTERNAL_GENLOCK 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_S2MM_SOF_ENABLE 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_S_AXIS_S2MM_TDATA_WIDTH 32U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_1 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_5 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_6 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_7 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_9 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_13 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_14 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_INFO_15 1U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_DEBUG_ALL 0U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ADDR_WIDTH 32U
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_ENABLE_VERT_FLIP 0U


/******************************************************************/

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0 */
#define XPAR_AXIVDMA_0_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_DEVICE_ID
#define XPAR_AXIVDMA_0_BASEADDR 0x7FC80000U
#define XPAR_AXIVDMA_0_HIGHADDR 0x7FC8FFFFU
#define XPAR_AXIVDMA_0_NUM_FSTORES 1U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S 1U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S_DRE 1U
#define XPAR_AXIVDMA_0_M_AXI_MM2S_DATA_WIDTH 32U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM 0U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM_DRE 0U
#define XPAR_AXIVDMA_0_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_MODE 0U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_MODE 0U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_0_INCLUDE_SG 0U
#define XPAR_AXIVDMA_0_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_0_USE_FSYNC 1U
#define XPAR_AXIVDMA_0_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_0_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXIVDMA_0_S2MM_LINEBUFFER_DEPTH 512U
#define XPAR_AXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 1U
#define XPAR_AXIVDMA_0_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_0_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXIVDMA_0_S_AXIS_S2MM_TDATA_WIDTH 32U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_13 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_0_c_addr_width 32U
#define XPAR_AXIVDMA_0_c_enable_vert_flip 0U


/******************************************************************/

/* Definitions for driver CLK_WIZ */
#define XPAR_XCLK_WIZ_NUM_INSTANCES 3

/* Definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0 */
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_DEVICE_ID 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_BASEADDR 0x7FC30000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_HIGHADDR 0x7FC3FFFF
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_CLOCK_MONITOR 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_USER_CLOCK0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_USER_CLOCK1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_USER_CLOCK2 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_USER_CLOCK3 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_REF_CLK_FREQ 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_USER_CLK_FREQ0 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_USER_CLK_FREQ1 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_USER_CLK_FREQ2 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_USER_CLK_FREQ3 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_PRECISION 1
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_PLL0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_ENABLE_PLL1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_PRIM_IN_FREQ 200.000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_NUM_OUT_CLKS 3


/* Definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1 */
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_DEVICE_ID 1
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_BASEADDR 0x7FC40000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_HIGHADDR 0x7FC4FFFF
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_CLOCK_MONITOR 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_USER_CLOCK0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_USER_CLOCK1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_USER_CLOCK2 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_USER_CLOCK3 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_REF_CLK_FREQ 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_USER_CLK_FREQ0 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_USER_CLK_FREQ1 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_USER_CLK_FREQ2 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_USER_CLK_FREQ3 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_PRECISION 1
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_PLL0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_ENABLE_PLL1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_PRIM_IN_FREQ 200.000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_NUM_OUT_CLKS 4


/* Definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2 */
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_DEVICE_ID 2
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_BASEADDR 0x7FC50000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_HIGHADDR 0x7FC5FFFF
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_CLOCK_MONITOR 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_USER_CLOCK0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_USER_CLOCK1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_USER_CLOCK2 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_USER_CLOCK3 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_REF_CLK_FREQ 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_USER_CLK_FREQ0 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_USER_CLK_FREQ1 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_USER_CLK_FREQ2 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_USER_CLK_FREQ3 100.0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_PRECISION 1
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_PLL0 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_ENABLE_PLL1 0
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_PRIM_IN_FREQ 200.000
#define XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_NUM_OUT_CLKS 1


/******************************************************************/

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0 */
#define XPAR_CLK_WIZ_0_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_0_DEVICE_ID
#define XPAR_CLK_WIZ_0_BASEADDR 0x7FC30000
#define XPAR_CLK_WIZ_0_HIGHADDR 0x7FC3FFFF
#define XPAR_CLK_WIZ_0_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_0_REF_CLK_FREQ 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ0 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ1 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ2 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ3 100.0
#define XPAR_CLK_WIZ_0_PRECISION 1
#define XPAR_CLK_WIZ_0_Enable_PLL0 0
#define XPAR_CLK_WIZ_0_Enable_PLL1 0
#define XPAR_CLK_WIZ_0_PRIM_IN_FREQ 200.000
#define XPAR_CLK_WIZ_0_NUM_OUT_CLKS 3

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1 */
#define XPAR_CLK_WIZ_1_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_1_DEVICE_ID
#define XPAR_CLK_WIZ_1_BASEADDR 0x7FC40000
#define XPAR_CLK_WIZ_1_HIGHADDR 0x7FC4FFFF
#define XPAR_CLK_WIZ_1_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_1_REF_CLK_FREQ 100.0
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ0 100.0
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ1 100.0
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ2 100.0
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ3 100.0
#define XPAR_CLK_WIZ_1_PRECISION 1
#define XPAR_CLK_WIZ_1_Enable_PLL0 0
#define XPAR_CLK_WIZ_1_Enable_PLL1 0
#define XPAR_CLK_WIZ_1_PRIM_IN_FREQ 200.000
#define XPAR_CLK_WIZ_1_NUM_OUT_CLKS 4

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2 */
#define XPAR_CLK_WIZ_2_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_CLOCK_GENERATION_CLK_WIZ_2_DEVICE_ID
#define XPAR_CLK_WIZ_2_BASEADDR 0x7FC50000
#define XPAR_CLK_WIZ_2_HIGHADDR 0x7FC5FFFF
#define XPAR_CLK_WIZ_2_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_2_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_2_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_2_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_2_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_2_REF_CLK_FREQ 100.0
#define XPAR_CLK_WIZ_2_USER_CLK_FREQ0 100.0
#define XPAR_CLK_WIZ_2_USER_CLK_FREQ1 100.0
#define XPAR_CLK_WIZ_2_USER_CLK_FREQ2 100.0
#define XPAR_CLK_WIZ_2_USER_CLK_FREQ3 100.0
#define XPAR_CLK_WIZ_2_PRECISION 1
#define XPAR_CLK_WIZ_2_Enable_PLL0 0
#define XPAR_CLK_WIZ_2_Enable_PLL1 0
#define XPAR_CLK_WIZ_2_PRIM_IN_FREQ 200.000
#define XPAR_CLK_WIZ_2_NUM_OUT_CLKS 1


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0U
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000U
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PS7_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/


/* Peripheral Definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_VIDEO_FORMATTER_0 */
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_VIDEO_FORMATTER_0_BASEADDR 0x7FC20000
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_VIDEO_FORMATTER_0_HIGHADDR 0x7FC2FFFF


/* Peripheral Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Peripheral Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Peripheral Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Peripheral Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Peripheral Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Peripheral Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Peripheral Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Peripheral Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Peripheral Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Peripheral Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Peripheral Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Peripheral Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Peripheral Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Peripheral Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Peripheral Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/* Peripheral Definitions for peripheral Z3660_0 */
#define XPAR_Z3660_0_BASEADDR 0x80000000
#define XPAR_Z3660_0_HIGHADDR 0x8FFFFFFF


/******************************************************************/


/* Canonical Definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_VIDEO_FORMATTER_0 */
#define XPAR_VIDEO_FORMATTER_0_BASEADDR 0x7FC20000
#define XPAR_VIDEO_FORMATTER_0_HIGHADDR 0x7FC2FFFF






































/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver I2STX */
#define XPAR_XI2STX_NUM_INSTANCES 1

/* Definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0 */
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_DEVICE_ID 0
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_BASEADDR 0x7FC10000
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_HIGHADDR 0x7FC1FFFF
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_DWIDTH 16
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_IS_MASTER 1
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_NUM_CHANNELS 1
#define XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_32BIT_LR 0


/******************************************************************/

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0 */
#define XPAR_XI2STX_0_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_DEVICE_ID
#define XPAR_XI2STX_0_BASEADDR 0x7FC10000
#define XPAR_XI2STX_0_HIGHADDR 0x7FC1FFFF
#define XPAR_XI2STX_0_DWIDTH 16
#define XPAR_XI2STX_0_IS_MASTER 1
#define XPAR_XI2STX_0_NUM_CHANNELS 1
#define XPAR_XI2STX_0_32BIT_LR 0


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Definition for input Clock */
/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_MM2S_INTROUT_INTR 62U
#define XPAR_FABRIC_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_IRQ_MM2S_INTR 65U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_AXIVDMA_0_VEC_ID XPAR_FABRIC_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_VIDEO_AXI_VDMA_0_MM2S_INTROUT_INTR
#define XPAR_FABRIC_AUDIO_FORMATTER_0_VEC_ID XPAR_FABRIC_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_AUDIO_FORMATTER_0_IRQ_MM2S_INTR

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0U
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100U
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FFU
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_PS7_SD_0_HAS_CD 1
#define XPAR_PS7_SD_0_HAS_WP 1
#define XPAR_PS7_SD_0_BUS_WIDTH 0
#define XPAR_PS7_SD_0_MIO_BANK 0
#define XPAR_PS7_SD_0_HAS_EMIO 0
#define XPAR_PS7_SD_0_SLOT_TYPE 0
#define XPAR_PS7_SD_0_CLK_50_SDR_ITAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_SDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_DDR_ITAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_DDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_100_SDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_200_SDR_OTAP_DLY 0


/******************************************************************/

#define XPAR_PS7_SD_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 1
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 0
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_SLOT_TYPE 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0
#define XPAR_XSDPS_0_CLK_50_SDR_ITAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_SDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_DDR_ITAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_DDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_100_SDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_200_SDR_OTAP_DLY 0


/******************************************************************/

/* Definitions for driver SYSMON */
#define XPAR_XSYSMON_NUM_INSTANCES 1U

/* Definitions for peripheral PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0 */
#define XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_IP_TYPE 0U
#define XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_DEVICE_ID 0U
#define XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_BASEADDR 0x7FC60000U
#define XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_HIGHADDR 0x7FC6FFFFU
#define XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_INCLUDE_INTR 1U


/******************************************************************/

/* Canonical definitions for peripheral PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0 */
#define XPAR_SYSMON_0_IP_TYPE 0U
#define XPAR_SYSMON_0_DEVICE_ID XPAR_PROCESSING_AV_SYSTEM_INTERCONNECT_MATRIX_XADC_WIZ_0_DEVICE_ID
#define XPAR_SYSMON_0_BASEADDR 0x7FC60000U
#define XPAR_SYSMON_0_HIGHADDR 0x7FC6FFFFU
#define XPAR_SYSMON_0_INCLUDE_INTR 1U


/******************************************************************/

/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 3U

/* Definitions for peripheral PS7_TTC_0 */
#define XPAR_PS7_TTC_0_DEVICE_ID 0U
#define XPAR_PS7_TTC_0_BASEADDR 0XF8001000U
#define XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_1_DEVICE_ID 1U
#define XPAR_PS7_TTC_1_BASEADDR 0XF8001004U
#define XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_2_DEVICE_ID 2U
#define XPAR_PS7_TTC_2_BASEADDR 0XF8001008U
#define XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Canonical definitions for peripheral PS7_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PS7_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xF8001000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PS7_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xF8001004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PS7_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xF8001008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definition for input Clock */
/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

#endif  /* end of protection macro */
