
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
 * The configuration table for devices
 */

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_SYSMON_0_DEVICE_ID,
		XPAR_SYSMON_0_BASEADDR,
		XPAR_SYSMON_0_INCLUDE_INTR,
		XPAR_SYSMON_0_IP_TYPE
	}
};


