M48
; DRILL file {KiCad 7.0.6-0} date 2024 October 04, Friday 20:33:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-04T20:33:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0701
%
G90
G05
T1
X5.3949Y-2.1398
X5.4949Y-2.1398
X5.5949Y-2.1398
X5.6949Y-2.1398
T0
M30
