#define STRINGIZER_(exp) #exp
#define STRINGIZER(exp) STRINGIZER_(exp)

char *zz_usb_cmd_str[]={
    [ZZUSB_CMD_NO_COMMAND  ] = STRINGIZER(ZZUSB_CMD_NO_COMMAND  ),
    [ZZUSB_CMD_CONTROL_XFER] = STRINGIZER(ZZUSB_CMD_CONTROL_XFER),
    [ZZUSB_CMD_BULK_XFER   ] = STRINGIZER(ZZUSB_CMD_BULK_XFER   ),
    [ZZUSB_CMD_INT_XFER    ] = STRINGIZER(ZZUSB_CMD_INT_XFER    ),
    [ZZUSB_CMD_ISO_XFER    ] = STRINGIZER(ZZUSB_CMD_ISO_XFER    ),
    [ZZUSB_CMD_RESET_PORT  ] = STRINGIZER(ZZUSB_CMD_RESET_PORT  ),
    [ZZUSB_CMD_RESUME_PORT ] = STRINGIZER(ZZUSB_CMD_RESUME_PORT ),
    [ZZUSB_CMD_SUSPEND_PORT] = STRINGIZER(ZZUSB_CMD_SUSPEND_PORT),
    [ZZUSB_CMD_ENUMERATE   ] = STRINGIZER(ZZUSB_CMD_ENUMERATE   ),
    [ZZUSB_CMD_QUERY_DEVICE] = STRINGIZER(ZZUSB_CMD_QUERY_DEVICE),
    [ZZUSB_CMD_SET_ADDRESS ] = STRINGIZER(ZZUSB_CMD_SET_ADDRESS ),
    [ZZUSB_CMD_CLEAR_STALL ] = STRINGIZER(ZZUSB_CMD_CLEAR_STALL ),
    [ZZUSB_CMD_CHECK_PORT  ] = STRINGIZER(ZZUSB_CMD_CHECK_PORT  ),
};

char *zz_usb_status_str[]={
    [ZZUSB_STATUS_OK      ] = STRINGIZER(ZZUSB_STATUS_OK      ),
    [ZZUSB_STATUS_PENDING ] = STRINGIZER(ZZUSB_STATUS_PENDING ),
    [ZZUSB_STATUS_ERROR   ] = STRINGIZER(ZZUSB_STATUS_ERROR   ),
    [ZZUSB_STATUS_TIMEOUT ] = STRINGIZER(ZZUSB_STATUS_TIMEOUT ),
    [ZZUSB_STATUS_STALL   ] = STRINGIZER(ZZUSB_STATUS_STALL   ),
    [ZZUSB_STATUS_NAK     ] = STRINGIZER(ZZUSB_STATUS_NAK     ),
    [ZZUSB_STATUS_CRC     ] = STRINGIZER(ZZUSB_STATUS_CRC     ),
    [ZZUSB_STATUS_BABBLE  ] = STRINGIZER(ZZUSB_STATUS_BABBLE  ),
    [ZZUSB_STATUS_OVERRUN ] = STRINGIZER(ZZUSB_STATUS_OVERRUN ),
    [ZZUSB_STATUS_UNDERRUN] = STRINGIZER(ZZUSB_STATUS_UNDERRUN),
    [ZZUSB_STATUS_OFFLINE ] = STRINGIZER(ZZUSB_STATUS_OFFLINE ),
    [ZZUSB_STATUS_BADPARAM] = STRINGIZER(ZZUSB_STATUS_BADPARAM),
};
