# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.cache/wt [current_project]
set_property parent.project_path C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/sources_1/new/version.vh
read_verilog -library xil_defaultlib {
  C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/sources_1/new/video_formatter.v
  C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/sources_1/new/cpuclk_iob.v
  C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/sources_1/new/z3660.v
  C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_2/design_1_axi_vdma_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_2/design_1_axi_vdma_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_2/design_1_axi_vdma_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_audio_formatter_0_0/design_1_audio_formatter_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_audio_formatter_0_0/design_1_audio_formatter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0_1/design_1_axi_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0_1/design_1_axi_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_i2s_transmitter_0_0/design_1_i2s_transmitter_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_i2s_transmitter_0_0/design_1_i2s_transmitter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_2/design_1_axi_register_slice_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_protocol_convert_0_0/design_1_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_193/design_1_s00_regslice_193_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_194/design_1_s00_regslice_194_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_192/design_1_s00_regslice_192_clocks.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_195/design_1_s00_regslice_195_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/constrs_1/imports/new/gpio_axi.xdc
set_property used_in_implementation false [get_files C:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.srcs/constrs_1/imports/new/gpio_axi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7z020clg400-3 -flatten_hierarchy none -retiming
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
