# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/gpio_axi.xdc

# XDC: new/debug.xdc

# XDC: new/timing.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_1 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_1 || ORIG_REF_NAME==design_1_axi_vdma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_video_formatter_0_0/design_1_video_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_video_formatter_0_0 || ORIG_REF_NAME==design_1_video_formatter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_0_1/design_1_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_0 || ORIG_REF_NAME==design_1_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_2 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_audio_formatter_0_0/design_1_audio_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_audio_formatter_0_0 || ORIG_REF_NAME==design_1_audio_formatter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_0_1/design_1_axi_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_0 || ORIG_REF_NAME==design_1_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_0 || ORIG_REF_NAME==design_1_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_transmitter_0_0/design_1_i2s_transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2s_transmitter_0_0 || ORIG_REF_NAME==design_1_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_3/design_1_axi_interconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_3 || ORIG_REF_NAME==design_1_axi_interconnect_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2_0 || ORIG_REF_NAME==design_1_clk_wiz_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_3_0 || ORIG_REF_NAME==design_1_clk_wiz_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cpuclk_iob_0_0/design_1_cpuclk_iob_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cpuclk_iob_0_0 || ORIG_REF_NAME==design_1_cpuclk_iob_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0_1/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dwidth_converter_0_0 || ORIG_REF_NAME==design_1_axi_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_protocol_convert_0_0/design_1_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_protocol_convert_0_0 || ORIG_REF_NAME==design_1_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_1 || ORIG_REF_NAME==design_1_axi_register_slice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_1_0 || ORIG_REF_NAME==design_1_axi_register_slice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_2/design_1_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_2 || ORIG_REF_NAME==design_1_xlconcat_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_z3660_0_0/design_1_z3660_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_z3660_0_0 || ORIG_REF_NAME==design_1_z3660_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0_1/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_118/design_1_s00_regslice_118.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_118 || ORIG_REF_NAME==design_1_s00_regslice_118} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_117/design_1_s00_regslice_117.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_117 || ORIG_REF_NAME==design_1_s00_regslice_117} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_119/design_1_s00_regslice_119.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_119 || ORIG_REF_NAME==design_1_s00_regslice_119} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_1 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_1 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_1/design_1_rst_ps7_0_200M_1_1_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_1 || ORIG_REF_NAME==design_1_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_1 || ORIG_REF_NAME==design_1_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_1/design_1_axi_vdma_0_1_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_2 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_1_2 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_1_2/design_1_rst_ps7_0_200M_1_2_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_audio_formatter_0_0/design_1_audio_formatter_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_audio_formatter_0_0 || ORIG_REF_NAME==design_1_audio_formatter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_audio_formatter_0_0/design_1_audio_formatter_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0_1/design_1_axi_register_slice_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_0 || ORIG_REF_NAME==design_1_axi_register_slice_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0_1/design_1_axi_register_slice_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_0 || ORIG_REF_NAME==design_1_axis_register_slice_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_i2s_transmitter_0_0/design_1_i2s_transmitter_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_i2s_transmitter_0_0 || ORIG_REF_NAME==design_1_i2s_transmitter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_i2s_transmitter_0_0/design_1_i2s_transmitter_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2_0 || ORIG_REF_NAME==design_1_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2_0 || ORIG_REF_NAME==design_1_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_2_0/design_1_clk_wiz_2_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_3_0 || ORIG_REF_NAME==design_1_clk_wiz_3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_3_0 || ORIG_REF_NAME==design_1_clk_wiz_3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_3_0/design_1_clk_wiz_3_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_200M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_200M_0/design_1_rst_ps7_0_200M_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dwidth_converter_0_0 || ORIG_REF_NAME==design_1_axi_dwidth_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_dwidth_converter_0_0_1/design_1_axi_dwidth_converter_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_protocol_convert_0_0/design_1_axi_protocol_convert_0_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_1 || ORIG_REF_NAME==design_1_axi_register_slice_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_1_0 || ORIG_REF_NAME==design_1_axi_register_slice_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_118/design_1_s00_regslice_118_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_118 || ORIG_REF_NAME==design_1_s00_regslice_118} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_117/design_1_s00_regslice_117_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_117 || ORIG_REF_NAME==design_1_s00_regslice_117} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_119/design_1_s00_regslice_119_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_119 || ORIG_REF_NAME==design_1_s00_regslice_119} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: c:/Users/shanshe/OneDrive/Escritorio/z3660/z3660.gen/sources_1/bd/design_1/design_1_ooc.xdc
