
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xi2stx.h"

/*
* The configuration table for devices
*/

XI2stx_Config XI2stx_ConfigTable[XPAR_XI2STX_NUM_INSTANCES] =
{
	{
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_DEVICE_ID,
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_BASEADDR,
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_DWIDTH,
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_IS_MASTER,
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_NUM_CHANNELS,
		XPAR_PROCESSING_AV_SYSTEM_AUDIO_VIDEO_ENGINE_I2S_TRANSMITTER_0_32BIT_LR
	}
};


