#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 26 13:10:17 CEST 2021
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 38fcf00d6cb7489cb5794bfad040b82a --incr --debug typical --relax --mt 8 --include "../../../../ZStorm.ip_user_files/bd/design_1/ip/design_1_xlconstant_0_0/sim" --include "../../../../ZStorm.ip_user_files/bd/design_1/ip/design_1_xlconstant_0_1/sim" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot zstorm_sim_behav xil_defaultlib.zstorm_sim xil_defaultlib.glbl -log elaborate.log
