#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 26 13:07:10 CEST 2021
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim zstorm_sim_behav -key {Behavioral:sim_1:Functional:zstorm_sim} -tclbatch zstorm_sim.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/shanshe/Desktop/ZStorm/zstorm_sim_behav.wcfg -log simulate.log
